### ISSUE TITLE
Home Navbar not working when on Blog page

### ISSUE THREAD

**Issue by ZeleOeO** [mikky-j/impact-website#3]
Actually none of the buttons are working, or going to the desired home page.
I guess it's because it's referencing main-body, which is index.html. I don't know.
This is what it shows when you hover over "Home" on the navbar

![Screen Shot 2023-04-17 at 8 39 18 AM](https://user-images.githubusercontent.com/105638320/232417444-f4c14667-57ad-4798-ab15-70c8c37215d7.png)

**Comment by mikky-j** [comment]
Yh that’s how it is in the original design but you can do a pr and fix it sha

**Comment by Nathan-Somto** [comment]
How far mikky-j , i opened an issue and created a pr but you didn't respond.
